### ISSUE TITLE
is there a pre-trained model with 16K sampling rate？

### ISSUE THREAD

**Issue by zuowanbushiwo** [BUTSpeechFIT/speakerbeam#3]
Hi 
    I want to do some comparison tests， thanks！

**Comment by zmolikova** [comment]
Hi,
Unfortunately, we don't have a pre-trained 16k model available. But it shouldn't be very difficult to modify the training recipe, as LibriMix also has a 16k version. You might want to double the kernel size and stride in the model when training with 16k data.

**Comment by zuowanbushiwo** [comment]
ok thanks for your suggestion
